export const carBrands=["A.e.c.",
    "Abarth",
    "Abc",
    "ABEL",
    "ABI ",
    "AC",
    "Ac cars",
    "Access",
    "ACE ",
    "ACE ",
    "Adly",
    "Adria ",
    "Adria ",
    "Advanced",
    "Aebi",
    "Aec",
    "Aeon",
    "Aermacchi",
    "AHP",
    "Airstream ",
    "Aixam",
    "AJP",
    "AJS",
    "Alfa Romeo",
    "Allis chalmers",
    "Alpine",
    "Alvis",
    "Ambassador",
    "Amc",
    "Ammann",
    "ANDOVER",
    "Antonio carraro",
    "Apache",
    "Applied sweeper",
    "Aprilia",
    "ARB",
    "Arctic cat ",
    "Ariel",
    "Ariens",
    "Armstrong",
    "Arronbrook ",
    "Artic cat",
    "Artisan",
    "Asia",
    "Askoll",
    "Aston Martin",
    "Atala",
    "Atlas ",
    "Atul",
    "Auburn",
    "Audi",
    "Ausa",
    "Austin",
    "Austin morris",
    "Austinhealey",
    "Auto Campers ",
    "Auto Union",
    "Autocruise ",
    "Auto-explore ",
    "Autohaus ",
    "Autohomes ",
    "Autosleeper",
    "Auto-sleepers ",
    "Auto-sleepers ",
    "Autostar ",
    "Auto-trail ",
    "Aveling & porter",
    "Aveling barford",
    "Avondale ",
    "Avondale ",
    "Awd",
    "Aws",
    "Axon",
    "B & i",
    "B+i",
    "Babboe",
    "Bad Island Toyz",
    "Bailey ",
    "Bailey ",
    "Bajaj",
    "Bamby",
    "Bamford",
    "Baotian",
    "Barford",
    "Barossa",
    "Bashan",
    "Basis",
    "Batavus",
    "Bateman",
    "Batribike",
    "Bavaria ",
    "Beameo",
    "Beauford",
    "BEDFORD",
    "Bedford ",
    "Bela ",
    "Belarus",
    "BENALU",
    "Benelli",
    "Benford",
    "Benimar ",
    "Benno Boost",
    "Bentley",
    "Bentley ",
    "Bergamont",
    "Berkeley",
    "Bessacarr ",
    "Bessacarr ",
    "Beta",
    "Better",
    "Bianchi",
    "Big Dog",
    "Bigbear",
    "Bilbos ",
    "Bimota",
    "Bitelli",
    "Bk Bluebird ",
    "Blaw knox",
    "Bluroc Motorcycles",
    "Bmc",
    "BMI",
    "BMW",
    "BMW",
    "BMW",
    "Bob cat",
    "Bobcat",
    "Bolinder",
    "Bollinger-munktells",
    "Bomag",
    "Bombardier",
    "Bond",
    "Boom",
    "Borgward",
    "Borum",
    "Boss",
    "Boss Hoss",
    "BOUGHTON",
    "Bova",
    "Bradford",
    "Bradshaw",
    "Branford",
    "Branson",
    "Bridgestone",
    "Briggs and stratton",
    "Bristol",
    "Bristol (blmc)",
    "Britax",
    "British trackstar",
    "Brixton",
    "Brockhurst",
    "Brompton",
    "BROSHUIS",
    "Brough Superior",
    "Brp",
    "BSA",
    "Bsa/triumph",
    "Buccaneer ",
    "Buccaneer ",
    "Buckler",
    "Buell",
    "Bugatti",
    "Buick",
    "Bullit",
    "Bullit Motorcycles",
    "Bultaco",
    "Bumblebee",
    "Burlington",
    "Burstner ",
    "Butchers & Bicycles",
    "BYD",
    "C s special",
    "C.v.s.",
    "Cadillac",
    "Cagiva",
    "Calder Leisure ",
    "Camper King ",
    "Campervan Warehouse ",
    "Camp-let ",
    "Can-Am",
    "Cannondale",
    "Cannondale Cycles",
    "Caofen",
    "Carado ",
    "Caravelair ",
    "Carbodies",
    "Caretta ",
    "Carmichael",
    "Carnaby ",
    "Carthago ",
    "CARTWRIGHT",
    "Carver",
    "Case",
    "Case international",
    "Case poclain",
    "Caterham",
    "Caterpillar",
    "CCM",
    "Ccs",
    "Cectek",
    "Celco profil",
    "Cf moto",
    "CFMOTO",
    "Ch racing",
    "Challenger ",
    "Champ",
    "Chang jiang",
    "Chausson ",
    "CHEREAU",
    "Chesil",
    "Chevrolet",
    "Chevrolet ",
    "Chevrolet ",
    "Chevrolet gmc",
    "CHIEFTAIN",
    "Chituma",
    "Chrysler",
    "Chunlan",
    "CI ",
    "Ci motorhome",
    "Citroen",
    "Citroen ",
    "Citroen ",
    "Citymaster",
    "Claas",
    "Clark",
    "Claud Butler",
    "Clayson",
    "CLAYTON",
    "Club car",
    "Coachman ",
    "Coachman ",
    "Coachmen",
    "Cobra",
    "Coles",
    "Colnago",
    "COLSON",
    "Colt",
    "Commander",
    "Commer",
    "Compass ",
    "Compass ",
    "CONCEPT",
    "Concorde ",
    "Conveyancer",
    "Conway ",
    "Corratec",
    "CORUS",
    "Corvette",
    "Cosalt ",
    "Cosmos",
    "Cossack",
    "Cotton",
    "Countax",
    "County comm cars",
    "Coventry climax",
    "Coventry eagle",
    "Cox",
    "CPI",
    "CRANE FRUEHAUF",
    "CROSSLAND",
    "Cub",
    "CUBE",
    "Cupra",
    "Cyclemaster",
    "Cz",
    "D.h. special",
    "D.m.w.",
    "Dacia",
    "Dacia ",
    "Daelim",
    "Daewoo",
    "DAF",
    "DAF ",
    "Daihatsu",
    "Daihatsu ",
    "Daimler",
    "Dajiang",
    "Dallian",
    "Dallingridge",
    "Damon ",
    "Danbury ",
    "Datsun",
    "David brown",
    "Dawes",
    "Dax",
    "Dayang",
    "Dayun",
    "De tomaso",
    "DEKER",
    "Delage",
    "Delta ",
    "Demag",
    "Denby ",
    "Dennis",
    "DENNIS EAGLE",
    "DENNISON",
    "Derbi",
    "Desiknio",
    "Desperate dan",
    "Dethleffs ",
    "Deutz fahr",
    "Devon ",
    "DFSK",
    "DFSK ",
    "Di blasi",
    "Di blassi",
    "Diamond",
    "Di-Blasi",
    "Dieci",
    "Direct Bike",
    "Direct bikes",
    "Dirt force",
    "Dirt pro",
    "Dkw",
    "Dmw",
    "Dodge",
    "Dodge ",
    "Dodge ",
    "Dodge (usa)",
    "Domino",
    "DON-BUR",
    "Dong feng",
    "Donkervoort",
    "Doosan",
    "Dormobile ",
    "Dot",
    "Douglas",
    "Dreamer ",
    "Ds",
    "DS Automobiles",
    "Ducati",
    "Ducati Cycles",
    "Ducato",
    "Dunelt",
    "Dutton",
    "Dynapac",
    "Eagle",
    "Easy Caravanning ",
    "Easy rider",
    "EAV",
    "EBCO",
    "Ebr",
    "E-City Wheels",
    "Ecooter",
    "Elddis ",
    "Elddis ",
    "Electra",
    "Electric Motion",
    "Electric motorsport",
    "Elnagh ",
    "Emax",
    "Emu",
    "Energica",
    "Enfield",
    "Eovolt",
    "Ep equipment",
    "Epc",
    "ERF",
    "Eriba ",
    "Eriba ",
    "E-Rider",
    "Eskuta",
    "Esoro",
    "Essex",
    "Estarli",
    "Eton",
    "Etrusco ",
    "Eura Mobil ",
    "European Caravans ",
    "EUROTRAILER",
    "Evari",
    "Excalibur",
    "Excelisor",
    "Excelsior",
    "Explorer",
    "Fabrique",
    "Factory",
    "Falcon",
    "Fantic",
    "Fantic Cycles",
    "Fantic motor",
    "FAYMONVILLE",
    "FB Mondial",
    "FELDBINDER",
    "Fendt ",
    "Fendt ",
    "Ferguson",
    "Fermec",
    "Ferrari",
    "Fiat",
    "Fiat ",
    "Fiat ",
    "Fiatagri",
    "Field marshall",
    "Fifth Wheel ",
    "Fleetwood ",
    "Fleetwood ",
    "Fleurette ",
    "Florium ",
    "Fn",
    "Focus",
    "FODEN",
    "Ford",
    "Ford ",
    "Ford ",
    "Ford roller team",
    "Fordson",
    "Fordsonmajor",
    "Forest River ",
    "Forme",
    "Foster",
    "Foton",
    "Francisbarne",
    "Francis-barnett",
    "Frankia ",
    "Fraser",
    "Frazer nash",
    "Frazier",
    "Freedom ",
    "Freestyle ",
    "Freight rover",
    "Freightliner ",
    "FRUEHAUF",
    "FSM",
    "Fso cars",
    "FUSO",
    "FUSO ",
    "Fym",
    "Gardner douglas",
    "Garelli",
    "Garia ",
    "Gas Gas",
    "Gas Gas Cycles",
    "GAZ ",
    "Gazelle",
    "Geist ",
    "Gem",
    "GENERAL TRAILER",
    "GENERAL TRAILERS",
    "GEOFF BURSE",
    "Giantco",
    "Gilera",
    "GILESKIPS",
    "GILESKIPS MANUFACTURERS LTD",
    "Gillet",
    "Gillet-herstal",
    "Ginetta",
    "Giott/line",
    "Giottiline ",
    "Globe car",
    "Globecamper ",
    "Globecar ",
    "Globestar ",
    "Globe-traveller ",
    "Glutton",
    "Gmc",
    "Go Pod ",
    "Gobur ",
    "Gocycle",
    "Going Uk ",
    "Go-kart",
    "GOLDHOFER",
    "Go-pod ",
    "Govecs",
    "Gpx",
    "GPX Moto",
    "Grasshopper",
    "GRAY & ADAMS",
    "Great Wall ",
    "Green machine",
    "Greeves",
    "Grinnall",
    "Grove",
    "Grove coles",
    "GRW",
    "Gsm",
    "Gulfstream ",
    "GURLESENYIL",
    "Guy",
    "H.r.d.",
    "Haibike",
    "Hako",
    "Hamm",
    "Hanway",
    "Haotian",
    "Harley-Davidson",
    "Harris",
    "HENRED FREUHAUF",
    "Her che",
    "Her chee",
    "Herald",
    "Herald Motor Co",
    "Herald motor company",
    "Hesketh",
    "Hillman",
    "Hillside Leisure ",
    "Himiway",
    "HINO",
    "Hitachi",
    "Hi-trac",
    "Hm moto",
    "Hobby ",
    "Hobby ",
    "Holden",
    "Holdsworth ",
    "Holeshot ",
    "Homecar ",
    "Honbike",
    "Honda",
    "Honda",
    "Honda ",
    "Honda ",
    "Hongdou",
    "Honley",
    "Horizon ",
    "Horwin",
    "Hotchkiss",
    "Hotomobil ",
    "HOUGHTON PARKHOUSE",
    "Howard",
    "Hsun",
    "Humber",
    "Hummer",
    "HUMVEE",
    "Huoniao",
    "Husaberg",
    "Husqvarna",
    "Hydrema",
    "Hydrocon",
    "Hymer ",
    "Hymer ",
    "Hyosung",
    "Hyster",
    "Hyundai",
    "Hyundai ",
    "Hyundai ",
    "Ibis",
    "Ideal",
    "Ifa multicar",
    "Ifamulticar",
    "IFOR WILLIAMS",
    "Ih Motorhomes ",
    "Imt",
    "Indian",
    "INDOX",
    "INEOS ",
    "Infiniti",
    "Inos ",
    "Internationa",
    "International",
    "Iris.bus",
    "Irizar",
    "Iseki",
    "Isuzu",
    "ISUZU",
    "Isuzu ",
    "Isuzu trucks",
    "Italjet",
    "Itineo ",
    "Iturri",
    "IVECO",
    "Iveco ",
    "Iveco ",
    "Iveco ford",
    "J.c.",
    "Jack allen",
    "Jago",
    "Jaguar",
    "James",
    "James comet",
    "Japauto",
    "Jawa",
    "Jayco ",
    "Jba",
    "Jcb",
    "Jeep",
    "Jeep ",
    "Jensen",
    "Jialing",
    "Jianshe",
    "Jincheng",
    "Jinling",
    "Jinlun",
    "Jinma",
    "Jlg",
    "Joa-camp ",
    "John allen",
    "John deere",
    "John fowler",
    "Johnson",
    "JOHNSTON",
    "Joint ",
    "Jonway",
    "Jotagas",
    "Jowett",
    "Joyner",
    "Jumbo",
    "Jzr",
    "Kaisar",
    "Kalkhoff",
    "Kalmar",
    "Kangda",
    "Karcher",
    "Karrier",
    "KASSBOHRER",
    "Kato",
    "Kawasaki",
    "Kazuma",
    "Keen",
    "Keeway",
    "KEL-BERG",
    "Kia",
    "Kiden",
    "KING",
    "King long",
    "Kingday",
    "Kinroad",
    "Kioti",
    "Knaus ",
    "Knaus ",
    "Kockums",
    "Kove",
    "Kramer",
    "Kramerallrad",
    "KRONE",
    "KSR Moto",
    "KTM",
    "KTM Cycles",
    "Kuberg",
    "Kubota",
    "Kuma Bikes",
    "Kurz",
    "Kymco",
    "Kynoch",
    "La Mancelle ",
    "La Strada ",
    "Lada",
    "LAG",
    "Lagonda",
    "Laika ",
    "LAMBERET",
    "Lambert",
    "Lamborghini",
    "Lambretta",
    "Lancer",
    "Lanchester",
    "Lancia",
    "Land Rover ",
    "Landini",
    "Landrover",
    "LANGENDORF",
    "Lansing bagnall",
    "Lansing linde",
    "Lansingbagna",
    "Lanz bulldog",
    "Lapierre",
    "Larry vs Harry Bullitt",
    "Laverda",
    "LAWRENCE DAVID",
    "LDV ",
    "LDV ",
    "Le Voyageur ",
    "Leeway",
    "LEGRAS",
    "Leisuredrive ",
    "LEVC",
    "LEVC ",
    "Levis",
    "Lexmoto",
    "Lexus",
    "Leyland",
    "Leyland aec",
    "LEYLAND DAF",
    "Leyland national",
    "Lhy",
    "Liebherr",
    "Lifan",
    "Lifton",
    "Lincoln",
    "Linde",
    "Liner",
    "Linhai",
    "Lion Caravans ",
    "Liv",
    "LMC ",
    "LMC ",
    "LML",
    "Locust",
    "Lomax",
    "Loncin",
    "London taxis int",
    "Longjia",
    "Lonsdale",
    "Lorain",
    "Lotus",
    "Lunar ",
    "Lunar ",
    "Lvneng",
    "Lvtong",
    "M & G",
    "MAC",
    "Machzone ",
    "Maeving",
    "Magirus deutz",
    "Magni",
    "MAGYAR",
    "Mahindra",
    "Maico",
    "MAKES",
    "Malaguti",
    "Malibu ",
    "MAN",
    "MAN ",
    "MAN ",
    "Man/vw",
    "Manet puch",
    "Manitou",
    "Manttx",
    "Manx norton",
    "Marcos",
    "Marin",
    "Marlin",
    "Marquis ",
    "Marshall",
    "Martin conquest",
    "Masai",
    "Maserati",
    "Mash",
    "Mash Motorcycles",
    "MASSEY",
    "Massey ferguson",
    "Massey-harris",
    "Matador",
    "Matbro",
    "Matchless",
    "Mathieu",
    "MAXUS",
    "MAXUS ",
    "Mazda",
    "Mazda ",
    "Mazda ",
    "Mbk",
    "MBP",
    "Mcc",
    "MCCAULEY",
    "Mccormick",
    "Mccormick international",
    "Mccoy",
    "McLaren ",
    "Mclellan",
    "Mclouis ",
    "Mcw",
    "Mecalac",
    "Meccanica",
    "Megelli",
    "MELTON",
    "Mercedes",
    "Mercedes-Benz",
    "Mercedes-Benz",
    "MERCEDES-BENZ",
    "Mercedes-Benz ",
    "Mercury",
    "Merida",
    "Merlo",
    "METALLIX",
    "Meteorite",
    "Metrocab",
    "Mev",
    "Mf industria",
    "Mf industrial",
    "MG",
    "MG ",
    "MGB",
    "Micro",
    "Microcar",
    "Midas",
    "Mig",
    "Miller ",
    "Mini",
    "MINI ",
    "Mini otter",
    "MiRider",
    "Mitsubishi",
    "MITSUBISHI",
    "Mitsubishi ",
    "Mitsubishi ",
    "Mitsubishi fuso",
    "Mk",
    "Mobilvetta ",
    "Mobylette",
    "Modenas",
    "Moke",
    "Moncayo ",
    "Mondial",
    "Mondraker",
    "Montesa",
    "Montesa honda",
    "MONTRACON",
    "Mooveo ",
    "Morelo ",
    "Morgan",
    "Morgan 3 wheeler",
    "Morini",
    "Morooka",
    "Morris",
    "Moss",
    "Moto Guzzi",
    "Moto Morini",
    "Moto roma",
    "Moto villa",
    "Motobecane",
    "Motoconfort",
    "Motorini",
    "Moto-trek ",
    "Moustache",
    "Moxy",
    "MULDOON",
    "Multione",
    "Murvi ",
    "Mutt",
    "Muz",
    "MV Agusta",
    "Mz",
    "Nanfang",
    "Necht",
    "Neco",
    "Neoplan",
    "Neval",
    "New holland",
    "New hudson",
    "New imperial",
    "New orleans",
    "Newbot",
    "Newbot storm 1",
    "Nfm",
    "Ng",
    "Niesmann + bischoff",
    "Niesmann And Bischoff ",
    "Ninja",
    "Nippi",
    "Nissan",
    "Nissan ",
    "Nissan ",
    "NIU",
    "Noble",
    "NOOTEBOOM",
    "Norco",
    "Norton",
    "Norton villiers",
    "Nostalgia cars",
    "Nsu",
    "Nu Venture ",
    "Nubodi",
    "Nuffield",
    "Nutfield",
    "Ok supreme",
    "OLDBURY",
    "Oldsmobile",
    "Omar ",
    "Opel",
    "Optare",
    "Opus ",
    "Ora",
    "Orbea",
    "Orion ",
    "OSET",
    "Oshkosh",
    "Ossa",
    "Other ",
    "Other ",
    "Other Cars",
    "Ovaobike",
    "OZGUL",
    "P+m",
    "Packard",
    "Panama ",
    "PANELTEX",
    "Panther",
    "Paton",
    "Paxster ",
    "Peel",
    "Pemberton ",
    "Pembleton",
    "Penman",
    "Pennine Leisure ",
    "Perodua",
    "Peugeot",
    "Peugeot",
    "Peugeot",
    "Peugeot ",
    "Peugeot ",
    "Pfautec",
    "Pgo",
    "Phoenix ",
    "Piaggio",
    "Piaggio ",
    "Piktou",
    "Pilgrim",
    "Pilote ",
    "Pinguely",
    "Pioneer ",
    "PLA ",
    "Platinum Wave ",
    "PLOWMAN",
    "Poclain",
    "Polaris",
    "Polestar",
    "Polski-fiat",
    "Pontiac",
    "Por",
    "Porsche",
    "Ppm",
    "Proteus",
    "Proton",
    "Puch",
    "Pulse",
    "Pure",
    "Pursang",
    "Puzey",
    "Pyrene",
    "Qingqi",
    "Quadski",
    "Quadzilla",
    "Quantum",
    "Quasar",
    "Raleigh",
    "RALFO",
    "Randger ",
    "Ransomes jacobsen",
    "Rapido ",
    "Rau",
    "Raw",
    "Raynal",
    "Rc Motorhomes ",
    "Reform",
    "Reformwerke",
    "Regal ",
    "Regent",
    "Reimo Cmc ",
    "Reliant",
    "Renault",
    "RENAULT",
    "Renault ",
    "Renault ",
    "Renault ",
    "Renault Trucks ",
    "Renegade",
    "Retreat ",
    "Reva",
    "Rewaco",
    "RFN",
    "RGNT",
    "Rhon",
    "Rickman",
    "Ridgeback",
    "Rieju",
    "Riese & Muller",
    "Riley",
    "Rimor ",
    "RMB ",
    "Robin hood",
    "Rocky Mountain",
    "Rolba",
    "ROLFO",
    "Roller Team ",
    "Rolling Homes ",
    "Rolls Royce",
    "Rolls/transit",
    "Rolls-royce",
    "Romahome ",
    "Romet",
    "Rooder m1",
    "ROTHDEAN",
    "Rover",
    "Royal",
    "Royal Alloy",
    "Royal Enfield",
    "Royale",
    "RS ",
    "Rudge",
    "Ruston",
    "R-vision ",
    "S And L Motorhomes ",
    "Saab",
    "Sachs",
    "Safari ",
    "Saic",
    "Saiting",
    "Sakura",
    "Same",
    "Sampo",
    "Samsung",
    "Sanderson",
    "Santana",
    "Sanya",
    "Sanyang",
    "Sao",
    "Sarolea",
    "Sarolea manx",
    "Scammell",
    "SCANIA",
    "SCARAB",
    "Schaffer",
    "SCHMIDT",
    "SCHMITZ",
    "Scomadi",
    "Scorpa",
    "Scott",
    "SDC",
    "SEA ",
    "SEAT",
    "SEAT",
    "Secma",
    "Seddon/atkinson",
    "Segway",
    "Setra",
    "Shansu",
    "Shelvoke",
    "Shelvoke & drewry",
    "Sherco",
    "Shineray",
    "Shire Conversions ",
    "Shire Homes ",
    "Siamoto",
    "Silence",
    "Silk",
    "Simca",
    "Simplon",
    "Simson",
    "Singer",
    "Sinnis",
    "Siromer",
    "Skoda",
    "Skygo",
    "Skyteam",
    "Slam",
    "Slingshot",
    "Smart",
    "Smc",
    "Solis",
    "Sommer",
    "Sonik",
    "SOR",
    "Sparta ",
    "Specialized",
    "SPITZER",
    "Sporttec ",
    "Sprite ",
    "Sprite ",
    "Spy racing",
    "SsangYong",
    "SsangYong ",
    "Standard",
    "Stark",
    "Stark varg",
    "STAS",
    "Sterling ",
    "Sterling ",
    "Stewart",
    "Steyr",
    "Stirling eco",
    "Stomp",
    "Stothert and pitt",
    "Stuart",
    "Subaru",
    "Suffolk",
    "Sukida",
    "Sumitomo",
    "Sun Living ",
    "Sunbeam",
    "Sunbeam-talbot",
    "Sunlight ",
    "Sunra",
    "Super",
    "Super Soco",
    "Superbyke",
    "Surge",
    "Surron",
    "Suzuki",
    "Suzuki",
    "Suzuki ",
    "Swift ",
    "Swift ",
    "Swm",
    "SWM Motorcycles",
    "Sym",
    "T.m.c.",
    "T.y.m",
    "TAB ",
    "Tabbert ",
    "Tadano",
    "Tafe",
    "Taiwan golden bee",
    "Talaria",
    "Talbot ",
    "Talbot ",
    "Talus",
    "Tamoretti",
    "Tasker",
    "Tata",
    "Tbm",
    "TCL",
    "Teahupoo ",
    "TEC ",
    "TEC ",
    "Temsa",
    "Tenaci-Wong",
    "Terberg",
    "Terex",
    "Tern",
    "Terrot",
    "Tesla",
    "TGB",
    "Tgs",
    "Thelmoco",
    "Thok",
    "THOMPSON",
    "Thor Motor Coach ",
    "Thornycroft",
    "Thumpstar",
    "Thwaites",
    "Tiffin Motorhomes ",
    "TIGER",
    "TIGER TRAILERS",
    "Timberland ",
    "Tinbot",
    "Tingdene ",
    "TITAN",
    "TM",
    "Tm racing",
    "Tomos",
    "Tong yang",
    "Toro",
    "Torrot",
    "Toyota",
    "Toyota ",
    "Toyota ",
    "Trabant",
    "Tracgrip",
    "Transcamper ",
    "Trek",
    "Tribute ",
    "Trigano ",
    "Trigano ",
    "Trikeshop",
    "Tri-tech",
    "Triton",
    "Triumph",
    "Trojan",
    "Tromox",
    "TRS",
    "Trsi trs",
    "TRUCKMATE",
    "Tula",
    "Turner-miesse",
    "Tvr",
    "Tym",
    "Ultima",
    "Ultra",
    "UM",
    "Unimog",
    "Universal",
    "Unknown",
    "Uqi",
    "Ural",
    "Urban",
    "Urban Arrow",
    "Ursus",
    "UTILITY",
    "VALLELY",
    "Valmet",
    "Valtra",
    "VAN HOOL",
    "Vanden plas",
    "Vanmaster ",
    "Vantage ",
    "Vanworx ",
    "Vauxhall",
    "Vauxhall ",
    "Vauxhall ",
    "Vectrix",
    "Velimotor",
    "Velocette",
    "Veloe",
    "Velosolex",
    "Velsar ",
    "Venture",
    "Verteci",
    "Vertigo",
    "Vespa",
    "Vespa (douglas)",
    "Victory",
    "Victory ",
    "Viking",
    "Vincent",
    "Vmoto",
    "Voge",
    "Vogele",
    "Volkswagen",
    "Volkswagen ",
    "Volkswagen ",
    "Volkswagen ",
    "Volt",
    "Volvo",
    "VOLVO",
    "Volvo ",
    "Vor",
    "Vulcan",
    "Waaijenberg",
    "Wacker neuson",
    "Walker",
    "Walker mower",
    "Wasp",
    "Weatherill",
    "Weidemann",
    "WEIGHTMASTER",
    "Weinsberg ",
    "Weinsberg ",
    "Wellhouse ",
    "Westfalia ",
    "Westfield",
    "Westwood",
    "WHALE",
    "WHEELBASE",
    "Wheelhome ",
    "White",
    "White knuckle",
    "Whitlock bros",
    "WILCOX",
    "Wildax ",
    "Willerby ",
    "Willys",
    "WILSON",
    "Wingamm ",
    "Wingamm ",
    "Winget",
    "Winnebago ",
    "Wirtgen",
    "Wirtgen hamm",
    "Wisper",
    "WK Bikes",
    "Wolseley",
    "Wraith",
    "Wrightbus",
    "Xingyue",
    "Xinling",
    "Xiongtai",
    "X-sport",
    "Yadea",
    "Yale",
    "Yamaha",
    "Yamaha Cycles",
    "Yamasaki",
    "Yanmar",
    "Yucon ",
    "Zastava",
    "Zero",
    "Zeths",
    "Zetor",
    "Zhenhua",
    "Zhongneng",
    "Znen",
    "Zongshen",
    "Zontes",
    "Zundapp",
    ]